before_script:
  - git config --global user.name 'arthur' 
  - git config --global user.email 'arthur@ciuyat.com'
  - git remote set-url origin http://arthur:$PERSONAL_ACCESS_TOKEN@192.168.110.130/arthur/unilink_execution.git
  - git remote set-url gitee https://arthur:the17thangel@gitee.com/unilink_1/UnilinkExecution.git


variables:
  GIT_TRACE: "1"
  GIT_CURL_VERBOSE: "1"
  TZ: "Asia/Shanghai"

stages:
  - sync

.sync_template: &sync_template
  script:
    - whoami
    - timedatectl set-timezone Asia/Shanghai
    - ls -l /home/gitlab-runner/.ssh
    - ssh-keyscan gitee.com >> /home/gitlab-runner/.ssh/known_hosts
    - git config --global user.name 'arthur' 
    - git config --global user.email 'arthur@ciuyat.com'
    - git fetch gitee
    - git checkout master
    - git push -f gitee master
    - git log gitee/master..HEAD

  tags:
    - sync_task

sync_to_gitee:
  stage: sync
  <<: *sync_template
  only:
    - master

sync_schedule:
  stage: sync
  <<: *sync_template
  only:
    - pushes
  before_script:
      - git clean -ffdx
      - git reset --hard
    



