variables:
  GIT_TRACE: "1"
  GIT_CURL_VERBOSE: "1"

stages:
  - sync

.sync_template: &sync_template
  script:
    - whoami
    - ls -l /home/gitlab-runner/.ssh
    - ssh-keyscan gitee.com >> /home/gitlab-runner/.ssh/known_hosts
    - git config --global user.email "arthur@ciuyat.com"
    - git config --global user.name "arthur"
    - git checkout master
    - git add .
    - git commit -m "sync from in-house server"
    - git push -f --verbose gitee master
  tags:
    - sync_task

sync_to_gitee:
  stage: sync
  <<: *sync_template
  only:
    - master


sync_schedule:
  stage: sync
  <<: *sync_template
  only:
    - pushes
  before_script:
    - git remote set-url origin http://arthur:$PERSONAL_ACCESS_TOKEN@192.168.110.130/arthur/unilink_execution.git


