variables:
  PCF_DEPLOY_REPO: "http://arthur:the17thangel@192.168.110.130/arthur/unilink_execution.git"
  GITEE_REPO: "https://arthur19q3:the17thangel@gitee.com/unilink_1/UnilinkExecution.git"
  PCF_DEPLOY_BRANCH: master
  PCF_COMMIT_USER_NAME: arthur
  PCF_COMMIT_USER_EMAIL: arthur@ciuyat.com

stages:
  - mergeCode

mergeCode:
  stage: mergeCode
  script:
    - echo "Starting mergeCode stage"

    - eval $(ssh-agent -s)

    - ssh-add /home/gitlab-runner/.ssh/id_rsa

    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    
    ##
    ## Configure git
    ##
    - git config --global user.email "$PCF_COMMIT_USER_EMAIL"
    - git config --global user.name "$PCF_COMMIT_USER_NAME"
    
    ##
    ## Remove existing remotes and add new ones
    ##
    - git remote remove origin || true
    - git remote remove gitee || true
    - git remote add origin "$PCF_DEPLOY_REPO"
    - git remote add gitee "$GITEE_REPO"
    
    ##
    ## Debugging: Print the remotes again to ensure they are set correctly

    - git remote -v
    
    ##
    ## Checkout and update branch
    ##
    - git checkout -B $PCF_DEPLOY_BRANCH
    
    ##
    ## Fetch full history from origin to avoid shallow update issues
    ##
    - git fetch origin || (sleep 5 && git fetch origin)
    
    ##
    ## Pull latest changes from origin and rebase
    ##
    - git pull --rebase origin $PCF_DEPLOY_BRANCH
    
    ##
    ## Pull latest changes from gitee and rebase
    ##
    - git fetch --unshallow
    - git pull --rebase gitee $PCF_DEPLOY_BRANCH || true
    
    ##
    ## Check if there are changes to push to origin
    ##
    - |
      if [ -z "$(git status --porcelain)" ]; then
        echo "No changes to push to origin"
      else
        echo "Pushing changes to origin"
        git push origin $PCF_DEPLOY_BRANCH
      fi
    
    ##
    ## Force push changes to gitee
    ##
    - git push gitee $PCF_DEPLOY_BRANCH 

  tags:
    - sync_task
