variables:
  PCF_DEPLOY_REPO: "http://arthur:the17thangel@192.168.110.130/arthur/unilink_execution.git"
  GITEE_REPO: "https://arthur19q3:the17thangel@gitee.com/unilink_1/UnilinkExecution.git"
  PCF_DEPLOY_BRANCH: master
  PCF_COMMIT_USER_NAME: arthur
  PCF_COMMIT_USER_EMAIL: arthur@ciuyat.com

stages:
  - prepare
  - mergeCode

prepare:
  stage: prepare
  script:
    - echo "Preparing environment"
    - eval $(ssh-agent -s)
    - ssh-add /home/gitlab-runner/.ssh/id_rsa
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - git config --global user.email "$PCF_COMMIT_USER_EMAIL"
    - git config --global user.name "$PCF_COMMIT_USER_NAME"
    - git remote remove origin || true
    - git remote remove gitee || true
    - git remote add origin "$PCF_DEPLOY_REPO"
    - git remote add gitee "$GITEE_REPO"
    - git remote -v
    - git checkout -B $PCF_DEPLOY_BRANCH
    - git fetch origin || (sleep 5 && git fetch origin)
    - git pull --rebase origin $PCF_DEPLOY_BRANCH || (sleep 5 && git pull --rebase origin $PCF_DEPLOY_BRANCH)
    - git fetch --unshallow || true
    - git pull --rebase gitee $PCF_DEPLOY_BRANCH || true

mergeCode:
  stage: mergeCode
  script:
    - echo "Starting mergeCode stage"
    - git status
    - |
      if [ -z "$(git status --porcelain)" ]; then
        echo "No changes to push to origin"
      else
        echo "Pushing changes to origin"
        git push origin $PCF_DEPLOY_BRANCH
      fi
    - git push gitee $PCF_DEPLOY_BRANCH
  tags:
    - sync_task
  GIT_STRATEGY: none
