variables:
  GIT_TRACE: "1"
  GIT_CURL_VERBOSE: "1"

stages:
  - sync

.sync_template: &sync_template
  script:
    - echo "$GIT_SSH_PRIVATE_KEY" | tr -d '\r' > /home/gitlab-runner/.ssh/id_rsa
    - chmod 600 /home/gitlab-runner/.ssh/id_rsa
    - ssh-keyscan gitee.com >> /home/gitlab-runner/.ssh/known_hosts
    - git config --global user.email "arthur@ciuyat.com"
    - git config --global user.name "arthur"
    - git remote remove gitee || true
    - git remote add gitee git@gitee.com:unilink_1/UnilinkExecution.git
    - git push -f gitee master
  tags:
    - sync_task

sync_to_gitee:
  stage: sync
  <<: *sync_template
  only:
    - master

sync_schedule:
  stage: sync
  <<: *sync_template
  only:
    - pushes
