variables:
  PCF_DEPLOY_REPO: "http://arthur:the17thangel@192.168.110.130/arthur/unilink_execution.git"
  GITEE_REPO: "https://arthur19q3:the17thangel@gitee.com/unilink_1/UnilinkExecution.git"
  PCF_DEPLOY_BRANCH: master
  PCF_COMMIT_USER_NAME: arthur
  PCF_COMMIT_USER_EMAIL: arthur@ciuyat.com
  SSH_USER: "gitlab-runner" # 你的SSH用户名
  SSH_HOST: "192.168.110.130" # 你的SSH主机IP地址

stages:
  - mergeCode

mergeCode:
  stage: mergeCode
  script:
    - echo "Starting mergeCode stage"
    
    ##
    ## Run ssh-agent (inside the build environment)
    ##
    - eval $(ssh-agent -s)
    
    ##
    ## Add the existing SSH key to the agent
    ##
    - ssh-add /home/gitlab-runner/.ssh/id_rsa

    ##
    ## Optionally disable host key checking. Be aware that by adding that
    ## you are susceptible to man-in-the-middle attacks.
    ##
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    
    ##
    ## Configure git
    ##
    - git config --global user.email "$PCF_COMMIT_USER_EMAIL"
    - git config --global user.name "$PCF_COMMIT_USER_NAME"
    
    ##
    ## Remove existing remotes and add new ones
    ##
    - git remote remove origin || true
    - git remote remove gitee || true
    - git remote add origin "$PCF_DEPLOY_REPO"
    - git remote add gitee "$GITEE_REPO"
    
    ##
    ## Debugging: Print the remotes again to ensure they are set correctly
    ##
    - git remote -v
    
    ##
    ## Checkout and update branch
    ##
    - git checkout -B $PCF_DEPLOY_BRANCH
    - git fetch origin --unshallow
    ##

    ## Force push changes to gitee
    ##
    - git push gitee $PCF_DEPLOY_BRANCH

    ##
    ## SSH into the server
    ##
    - ssh -tt -i /home/gitlab-runner/.ssh/id_rsa -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST

  tags:
    - sync_task
