[package]
name = "unilink_execution"
version = "0.1.0"
edition = "2021"

[dependencies]
# Logging
tracing = "0.1.36"

# Data Source
clickhouse = "0.11.6"
# Rand
rand_distr = "0.4.3"
# Async
tokio = { version = "1.17.0", features = ["sync", "macros", "rt-multi-thread"] }
tokio-stream = { version = "0.1.9", features = ["sync"] }
tokio-tungstenite = { version = "0.21.0", features = ["rustls-tls-webpki-roots"] }
futures = "0.3.21"
async-trait = "0.1.57"
pin-project = "1.0.10"
reqwest = { version = "0.12.4", features = ["rustls-tls", "json"] }
async-stream = "0.3"
# Error
thiserror = "1.0.32"

# SerDe
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"

# Misc
uuid = { version = "1.8.0", features = ["v4", "serde"] }
chrono = { version = "0.4.22", features = ["serde"] }
parking_lot = "0.12.1"
num-traits = "0.2.15"
rand = "0.8.5"
rust_decimal = "1.35.0"
regex = { version = "1.10.0",features = ["unicode-perl"] }
futures-core = "0.3.30"
pin-utils = "0.1.0"
