margin_mode = "SimpleMode"
position_direction_mode = "NetMode"
position_margin_mode = "Isolated"
commission_level = "Lv2"
funding_rate = 0.0001
account_leverage_rate = 100.0  # Example leverage rate
execution_mode = "Backtest"

[fees_book]
spot = { maker_fees = 0.001, taker_fees = 0.002 }
perpetual = { maker_fees = 0.0005, taker_fees = 0.001 }