edition = "2021"
max_width = 150
binop_separator = "Front"
blank_lines_lower_bound = 0
brace_style = "AlwaysNextLine"
color = "Always"
combine_control_expr = false
control_brace_style = "ClosingNextLine"
format_code_in_doc_comments = true
doc_comment_code_block_width = 150
format_macro_matchers = true
indent_style = "Visual"
match_arm_leading_pipes = "Always"
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
trailing_semicolon = false
merge_imports = true
imports_granularity = "Crate"
imports_layout  = "Mixed"